### ISSUE TITLE
Canvas draws above where mouse is.

### ISSUE THREAD

**Issue by rberman** [rberman/Synesthesia#1]
The drawing on the canvas appears an inch or two over where the mouse is drawing.  When we don't modify the variables startX, startY, endX, and endY (part of line object) to be between 0 and 100, then the line draws in the correct place, but it doesn't play music.  Right now, either we can get it to play music, or we can get the canvas to draw in the right place.  We want both.

**Comment by mjaminbook** [comment]
hmm, I get the line displacement either way, as long as I'm scrolled down
to the play button. The line object doesn't look like it should actually
affect the line being drawn. It looks like it is just storing the line, not
being used to store it.

**Comment by rberman** [comment]
Actually, the displacement is a result of scrolling down the screen.  This bug won't exist when we get rid of divs outside the canvas, so that the canvas just takes up the whole screen.  Coolness.
