### ISSUE TITLE
Color Button's Purpose Unclear

### ISSUE THREAD

**Issue by mjaminbook** [rberman/Synesthesia#11]
We should add an icon of sorts to the color button to indicate it is for drawing. People have said that its purpose is unclear

**Comment by rberman** [comment]
I've updated the button to be an icon, so we should see if that helps users understand what it is.

**Comment by rberman** [comment]
Button is updated to a paintbrush. I think it's pretty clear, so I'm gonna close the issue for now, but if there's further confusion we can always change it very easily.
