### ISSUE TITLE
Not drawing on phone

### ISSUE THREAD

**Issue by mjaminbook** [rberman/Synesthesia#5]
All touch events work, but no drawing is made when there is a finger drag. When Kevin and I printed the currX value, it was NaN. There must be some compatibility issue when it comes to using event.clientX

**Comment by mjaminbook** [comment]
It might be because ng-mousemove provides coordinates for clientX in its event but on-drag does not. Maybe there is an equivalent?

**Comment by bretjackson** [comment]
You may need:
event.gesture.center.pageX/Y

https://forum.ionicframework.com/t/drag-element-and-move-it-around-performances-and-animation/13389
